# Generated by Django 5.1.6 on 2025-03-01 09:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', ckeditor.fields.RichTextField()),
                ('back', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
