# Generated by Django 5.1.6 on 2025-03-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0003_rename_create_time_flashcard_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='box',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
