# Generated by Django 5.1.6 on 2025-03-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0005_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='flashcards', to='cards_app.deck'),
            preserve_default=False,
        ),
    ]
